### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [koryga2012/Bootstrap#1]
1)
отступ
![image](https://user-images.githubusercontent.com/8464662/76964201-04026f00-692b-11ea-981e-64e4fb842f09.png)

2)
что с цифрой?
![image](https://user-images.githubusercontent.com/8464662/76964275-21373d80-692b-11ea-8820-942c1df5d4e8.png)

3)
перенос должен быть без отрыва бэйджа
![image](https://user-images.githubusercontent.com/8464662/76964295-2b593c00-692b-11ea-94d4-e417c52a0ffb.png)

4)
блок дублируется внизу
![image](https://user-images.githubusercontent.com/8464662/76964348-3e6c0c00-692b-11ea-8999-56bb37e5c699.png)

**Comment by koryga2012** [comment]
вроде бы исправил
https://koryga2012.github.io/Bootstrap/ - результат
https://github.com/koryga2012/Bootstrap - репозиторий

**Comment by Alecto** [comment]
3 не исправлено
4 не исправлено, вход должен быть вверху, а не внизу.

**Comment by koryga2012** [comment]
теперь точно все исправил
https://github.com/koryga2012/Bootstrap - репозиторий
https://koryga2012.github.io/Bootstrap/ - результат

**Comment by Alecto** [comment]
5)
не соответствует задаче
![image](https://user-images.githubusercontent.com/8464662/77451280-20a41880-6dfd-11ea-95a0-924ea256ba2c.png)

**Comment by Alecto** [comment]
новая ошибка, там же

вт, 24 бер. 2020 о 17:11 koryga2012 <notifications@github.com> пише:

**Comment by koryga2012** [comment]
а где новая ошибка?

**Comment by koryga2012** [comment]
вроде бы исправил
https://koryga2012.github.io/Bootstrap/  - результат
https://github.com/koryga2012/Bootstrap  - репозиторий

**Comment by Alecto** [comment]
не исправлено + слетает центрирование
![image](https://user-images.githubusercontent.com/8464662/77660207-b23c9300-6f81-11ea-8a95-6d798fd4bbb1.png)
![image](https://user-images.githubusercontent.com/8464662/77660214-b7014700-6f81-11ea-8375-20b4fa0d2eb8.png)

**Comment by Alecto** [comment]
не исправлено, отписал там же

чт, 26 бер. 2020 о 16:37 koryga2012 <notifications@github.com> пише:

**Comment by koryga2012** [comment]
окей, а тогда каков должен быть результат?
просто у вас в примере было так же, вроде бы...

**Comment by Alecto** [comment]
Нет, у меня не так.

Чт, 26 бер. 2020, 17:37 користувач koryga2012 <notifications@github.com>
пише:

**Comment by koryga2012** [comment]
https://github.com/koryga2012/Bootstrap - репозиторий
https://koryga2012.github.io/Bootstrap/ - результат
исправил

**Comment by Alecto** [comment]
отлично.
последний вопрос - кому ставить работу?
koryga2012 - в журнале не находится ))))

пт, 27 бер. 2020 о 15:22 koryga2012 <notifications@github.com> пише:

**Comment by koryga2012** [comment]
олейник вячеслав)

пт, 27 мар. 2020 г. в 15:40, Andrey <notifications@github.com>:

**Comment by Alecto** [comment]
Принято)

Пт, 27 бер. 2020, 15:47 користувач koryga2012 <notifications@github.com>
пише:
